### ISSUE TITLE
Extremly slow loading time when enable "Fetch from CSP"

### ISSUE THREAD

**Issue by brakim** [dukereborn/cmum#1]
As soon i enable "Fetch data from CSP" cmum becomes inaccessible. It takes about 5-10min to load a single page.

But if i disable it in the database, cmum runs smooth again.
I've been trying to read the php logs, but i get no errors, only a warning om the percent() function that i tries to divied something by zero. I wrote my own fix for that but nothing changes.

CSP version: 0.9.0 (build 244)

**Comment by dukereborn** [comment]
Set `<ghttpd enabled="false">` in your csp config under the <rmi> section. Check the readme file under "Trouble using cmum with the latest csp version?" for more information.

**Comment by brakim** [comment]
I have tried that also. 

``` <rmi>
    <display-name>Csproxy1</display-name>
    <status-web>
      <listen-port>8082</listen-port>
      <ssl enabled="false"> 
        <keystore password="secret">etc/csp_keystore</keystore>
      </ssl>
      <csp-connect enabled="true" debug="false" ignore-cache-requests="false"/>
      <war-file>lib/cs-status.war</war-file>
      <super-users>admin</super-users>
      <ghttp enabled="false"></ghttp>
    </status-web>
  </rmi>
```

**Comment by dukereborn** [comment]
Remember to restart csp after editing this part of the config file. Does your csp proxy config looks something like this:

```
<rmi>
  <display-name>PROXY</display-name>
  <status-web>
    <listen-port>12345</listen-port>
    <ssl enabled="true"> 
      <keystore password="secretpassword">etc/csp_keystore</keystore>
    </ssl>
    <war-file>lib/cs-status.war</war-file>
    <super-users>admin</super-users>
    <ghttp enabled="false">
      <alternate-port>8083</alternate-port>
      <log-file>log/ghttp-access.log</log-file>
      <feeder-password>secret1</feeder-password>
      <open-access-password>secret2</open-access-password>
    </ghttp>
  </status-web>
</rmi>
```

**Comment by brakim** [comment]
I now feel like a douche....

Restart of csp did the trick, thank you!

**Comment by dukereborn** [comment]
Glad it helped :)
